kind: ConfigMap
apiVersion: v1
metadata:
  name: microservice-config-volume
data:
  application.yml: |-
    bytewood:
      enviro: kubernetes
      secret: passphrase
    management:
      security:
        enabled: false
    spring:
      application:
        name: microservice
      jackson:
        serialization:
          WRITE_DATES_AS_TIMESTAMPS: false
