kind: Service
apiVersion: v1
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
